name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 6faa48a358ead15ea4b86798aa832a4820dfbe4e

    - name: Build C Code
      run: |
       make
